### ISSUE TITLE
Consider a mirror on GitBook?

### ISSUE THREAD

**Issue by stiven-ding** [qqfly/how-to-learn-robotics#1]
First I would like to sincerely thank you for your work. 

From my perspective of view, tutorials like this passage will get a much better experience to read on platforms like GitBook, rather than code version ones like Github. Besides, licenses like Creative Commons 4.0 may better protect your work than ones designed to prevent codes from plagiarizing.

Whatever, thanks again for your help to robotics learners by writing this great tutorial.

**Comment by qqfly** [comment]
Thank you for your advice. I have created a mirror of current master branch on [GitBook](https://qiu6401.gitbook.io/how-to-learn-robotics/).
