### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by ghost** [qqfly/how-to-learn-robotics#2]
Hi all, somebody can translate this into English? Translate, please. Thank you for listening.

**Comment by ghost** [comment]
Tell me, maybe there are the same repositories about robotics in English :sos:

**Comment by qqfly** [comment]
Sorry, I don't have time to do the translation in following months. I just added it to [todo list](https://github.com/qqfly/how-to-learn-robotics/blob/master/TODOs.md). And I hope there would be some volunteers can do the translation.

Besides, If you are interested in Robotics, the following links can be helpful:

- [Introduction to Robotics](https://www.youtube.com/watch?v=0yD3uBshJB0&list=PL64324A3B147B5578)
- [Penn's Robotics Specialization](https://www.coursera.org/specializations/robotics)
- [Modern Robotics](http://hades.mech.northwestern.edu/index.php/Modern_Robotics)

**Comment by ghost** [comment]
@qqfly Thank you so much!
